#!/usr/bin/python
import sys
from gtts import gTTS
import os
#import argparse

#parser=argparse.ArgumentParser(
#    description='''Talk To Speech Created by Chris Larry. ''',
#    epilog="""example: tts en "hello world" """)
#parser.add_argument('--foo', type=int, default=42, help='FOO!')
#parser.add_argument('el', nargs='*', default=[1, 2, 3], help='for Greek')
#parser.add_argument('en', nargs='*', default=[1, 2, 3], help='for UK English')
#parser.add_argument('en-us', nargs='*', default=[1, 2, 3], help='for US English')
#parser.add_argument('en-au', nargs='*', default=[1, 2, 3], help='for Australia English')
#parser.add_argument('it', nargs='*', default=[1, 2, 3], help='for Italian')
#args=parser.parse_args()
file1 = "asd.mp3"
lang = sys.argv[1]
name = sys.argv[2]
tts = gTTS(name, lang)
tts.save(file1)
os.system("mpv " + file1)
